# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: wandyezj Blog
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Random Thoughts
# baseurl: /docs # the subpath of your site, e.g. /blog
url: https://wandyezj.github.io # the base hostname & protocol for your site, e.g. http://example.com
domain: wandyezj.github.io
# twitter_username: wandyezj
github_username: wandyezj
# linkedin_username: wandyezj

# Build settings
markdown: GFM
theme: minima
plugins:
  - jekyll-feed

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - all.md
  - tags.md
  - recipes.md
  - read.md
  - links.md

# https://jekyllrb.com/docs/collections/
collections:
  recipes:
    output: true
  books:
    output: false
    title: ""
    author: ""
    # Year first published.
    year: ""
    # Link to wikipedia of the work, or the author.
    wiki: ""
    # {academic, literature, experience}
    genre: "" 
    # citation for original work
  papers:
    output: false
    title: ""
    author: ""
    year: ""
    link: ""
    tags: []
  essays:
    output: false
    title: ""
    author: ""
    year: ""
    link: ""
    tags: []
  products:
    output: true
    title: ""
    category: ""
    year: ""
    manufacturer: ""
    tags: []
    # compost - every part of the product and packaging must be compostable
    # recycle - every part of the product must be recyclable
    # landfill - if any part of the product must go in the landfill
    disposal: ""
    review: ""
  thoughts:
    output: true
    title: ""
    date: ""
    tags: []
  quotes:
    output: false
    # (required)
    quote: ""
    # (optional) author of the quote
    author: ""
    # (optional) citation of where the quote is from
    citation: ""
    # (optional) link to work
    link: ""


defaults:
  -
    scope:
      type: recipes # a collection in your site, in plural form
    values:
      layout: post
  -
    scope:
      type: products # a collection in your site, in plural form
    values:
      layout: post
  -
    scope:
      type: thoughts
    values:
      layout: post